### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by TheBestTvarynka** [TheBestTvarynka/homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by TheBestTravynka** [comment]
Contact information:
Pavlo Myroniuk
* https://www.facebook.com/cooperative.qkation
* pspos.developqkation@gmail.com
* https://t.me/TheBestTvarynka
* https://github.com/TheBestTvarynka
* https://www.linkedin.com/in/thebesttvarynka

**Comment by TheBestTvarynka** [comment]
:wave:
