### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by TheBestTvarynka** [TheBestTvarynka/homepage#7]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by TheBestTravynka** [comment]
EXPERIENCE

QStyleSheet https://github.com/TheBestTvarynka/QStyleSheetString
Data structure https://github.com/TheBestTvarynka/DataStructure
Ubiquitous-spark https://github.com/TheBestTvarynka/ubiquitous-spark
List-SQL-Parser https://github.com/TheBestTvarynka/Lisp-SQL-Parser

**Comment by TheBestTravynka** [comment]
PUBLICATIONS

none.

**Comment by TheBestTravynka** [comment]
ACHIEVEMENTS
2019 participating in Google HashCode19 (5th place in Kyiv)
2019 KPI Open (10th place)
2020 participating in Google HashCode20 (99th place in Ukraine (from 394))

**Comment by TheBestTravynka** [comment]
EDUCATION

2015 - 2018 studying in Volyn Scientific Boarding School of Volyn Regional Council
2018 - 2022 studying in National Technical University of Ukraine “Igor Sikorsky Kyiv Polytechnic Institute”

Cisco Networking https://coursera.org/share/cd58e79deec6b380a7fb1670f8112d72
Programming Languages https://coursera.org/share/2cfb7904737c0c18045773a2b6826bd4
Google Cloud Platform Fundamentals: Core Infrastructure https://coursera.org/share/8d99a69b1ac53e59a0661e47157ab527
Networking in Google Cloud: Defining and Implementing Networks https://coursera.org/share/f6b958c1503e4502c4d7d69b4c6ebfb2

The purpose of life is to improve something. My Purpose is to write new and improve existing software.

LANGUAGES
Ukraine
Russian
English

SKILLS
C++ Java JavaScript Bash Linux (Arch Linux) SQL PostgreSQL GCP Networking

**Comment by TheBestTvarynka** [comment]
:1st_place_medal:
